CREATE TABLE IF NOT EXISTS "View"(
  "id" SERIAL PRIMARY KEY,
  "userId" INTEGER REFERENCES "User"(id) ON DELETE CASCADE NOT NULL,
  "viewId" INTEGER REFERENCES "User"(id) ON DELETE CASCADE NOT NULL
);