CREATE TABLE IF NOT EXISTS "Like" (
  "id" SERIAL PRIMARY KEY,
  "userId" INTEGER REFERENCES "User"(id) ON DELETE CASCADE NOT NULL,
  "postId" INTEGER REFERENCES "Post"(id) ON DELETE CASCADE NOT NULL
)