CREATE TABLE IF NOT EXISTS "Comment" (
  "id" SERIAL PRIMARY KEY,
  "comment" VARCHAR NOT NULL,
  "postId" INTEGER REFERENCES "Post"(id) ON DELETE CASCADE NOT NULL,
  "userId" INTEGER REFERENCES "User"(id) ON DELETE CASCADE NOT NULL,  
  "createdAt" DATE NOT NULL,
  "updatedAt" DATE NOT NULL
);