CREATE TABLE IF NOT EXISTS "Block" (
  "id" SERIAL PRIMARY KEY,
  "userId" INTEGER REFERENCES "User"(id) ON DELETE CASCADE NOT NULL,
  "blockedId" INTEGER REFERENCES "User"(id) ON DELETE CASCADE NOT NULL
)